### ISSUE TITLE
Alfred wieder auf den Gateways installieren

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/Ansible-Freifunk-Gateway#11]
Wie Remü-07 mit einer Laufzeit von 127 Tagen zeigt, ist Alfred nicht Schuld an den Serverabstürzen. Daher könnten wir es wieder installieren, jedoch nur als Client.

```
alfred -i bat0 -b bat0 -m

-m -> Kommt weg
-b -> brauchen wir glaube ich auch nicht
-i -> Prüfen ob vielleicht sogar eine Alfredinstanz für alle Domänen reicht
```

**Comment by MPW1412** [comment]
@descilla, @H4ndl3, brauchen wir das noch, oder macht das Simons neue Respondd-Implementation?

**Comment by HellMar** [comment]
Das macht Respondd...

**Comment by descilla** [comment]
Nope, kann weg.

**Comment by MPW1412** [comment]
WONT-FIX.
