### ISSUE TITLE
sites-available fehlt

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/Ansible-Freifunk-Gateway#14]
```
TASK [services_nginx : Konfig-Datei default-init kopieren] *********************
fatal: [services]: FAILED! => {"changed": false, "checksum": "524e9847b8bbe3d4c7c639007aaf7744a28836f1", "failed": true, "msg": "Destination directory /etc/nginx/sites-available does not exist"}

```

sites-enabled fehlt auch

**Comment by MPW1412** [comment]
Scheint wohl nur in Zusammenhang mit einer neueren nginx-Version als Debian 8 aufzutreten:

# nginx Source

deb http://nginx.org/packages/debian/ jessie nginx
deb-src http://nginx.org/packages/debian/ jessie nginx

**Comment by HellMar** [comment]
Rolle existiert nicht mehr. Bzw wird nicht mehr eingesetzt.
