### ISSUE TITLE
hook: session.pre-down

### ISSUE THREAD

**Issue by paulinsche** [FreiFunkMuenster/Ansible-Freifunk-Gateway#17]
The session.pre-down calls the script with less options, than assumed by: Ansible-Freifunk-Gateway/gateways_l2tp/files/delif.sh

The scripts fails (every time) as there is noch Option $9. The script assumes, that $9 has information about the used client-bridge, that in turn ist derived from the port the client has conneced to.

I think the information ist in $3. Try this:

```
#!/bin/bash
INTERFACE="$3"
BRLINK=$(readlink /sys/class/net/${INTERFACE}/master)
DOM=${BRLINK#../}
brctl delif ${DOM} ${INTERFACE}

```

**Comment by MPW1412** [comment]
Dank @larsbu repariert.

**Comment by MPW1412** [comment]
Ach, es muss noch das delif.sh angepasst werden.

**Comment by MPW1412** [comment]
Kommando zurück. Da ist es schon korrekt drin. Man sollte sowas nicht auf dem Telefon bearbeiten. :)
