### ISSUE TITLE
Tunneldigger: Port-Patch Down

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/Ansible-Freifunk-Gateway#19]
Beim Tunneldigger-Patch ist nur die Funktion gepatcht, die die Verbindung aufbaut.

Die die sie abbaut sollte auch gepatcht werden. Dazu gehört auch das Skript delif.sh.

**Comment by larsbu** [comment]
Duplikat von Issue #17

**Comment by MPW1412** [comment]
Danke für die Info.
