### ISSUE TITLE
Batctl baut nicht mehr

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/Ansible-Freifunk-Gateway#25]
Batctl baut mit checkinstall irgendwie nicht mehr

Überprüfen und reparieren.

Ggfs. direkt die neue Version nehmen.

**Comment by descilla** [comment]
Ja, wir sollten die batctl Version dringend aktualisieren. In batadv 2016.4 (oder 2016.3) ist der Support für debugfs wohl rausgeflogen, stattdessen wird netlink für die Kommunikation mit dem Kernel verwendet. Das kann die Version 2015.1 nicht. Ich prüfe, ob batctl 2016.4 abwärtskompatibel ist und passe die Rollen dann entsprechend an. Falls nicht muss ich mir noch etwas andere überlegen.

**Comment by descilla** [comment]
Im letzten Commit ( aae78182fb096976214cf87c71b85b86dc380f8e ) gefixt. Es wird jetzt geprüft welche Version installiert und ggf. neu gebaut. Den "networking restart" trigger habe ich an dieser Stelle entfernt (der wird ja eh bei Änderungen an dem nachfolgenden Template eh ausgelöst). Außerdem habe ich die Abhängigkeit "libnl-genl-3-dev" hinzugefügt, sodass batctl jetzt auch wieder baut.
