### ISSUE TITLE
Mehrfachgeneration der statischen V6-Routen

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/Ansible-Freifunk-Gateway#26]
Wenn ein Backway über ffms_tun_to noch ein reines Gateway anbindet, können die statischen IPV6-Routen mehrfach auftreten.

So derzeit z. B. bei Des2.

**Comment by descilla** [comment]
Fixed by commit 3cf1843594af354f1b39f8fb250d1d3e0bc82691
