### ISSUE TITLE
Always install linux-headers when upgrading kernel-version

### ISSUE THREAD

**Issue by descilla** [FreiFunkMuenster/Ansible-Freifunk-Gateway#32]
We should always install linux-headers besides linux-image to provide extra kernel modules maybe installed by the gateways owner.

**Comment by HellMar** [comment]
@descilla sollte das nicht hier:
https://github.com/FreiFunkMuenster/Ansible-Freifunk-Gateway/blob/master/backports-kernel/tasks/main.yml#L22
passieren?

**Comment by MPW1412** [comment]
Wir arbeiten nicht mehr mit Backports-Kerneln.
