### ISSUE TITLE
Batctl bauen scheitert, wenn ältere Version installiert

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/Ansible-Freifunk-Gateway#40]
Moin,

das Bauen von batctl scheitert, wenn schon eine ältere Version installiert ist:

```
TASK [gateways_batman : batctl bauen] ******************************************
fatal: [gw03]: FAILED! => {"failed": true, "msg": "The conditional check 'batctl.stat.exists == False or batctl_version.stdout_lines[0] != \"batctl 2016.4\"' failed. The error was: error while evaluating conditional (batctl.stat.exists == False or batctl_version.stdout_lines[0] != \"batctl 2016.4\"): 'dict object' has no attribute 'stdout_lines'\n\nThe error appears to have been in '/home/mpw/gits/ansible-fflip/roles/gateways_batman/tasks/main.yml': line 25, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: batctl bauen\n  ^ here\n"}
```

Müssen wir uns mal anschauen: Es sollte erst ermittelt werden, welche Version installiert ist und wenn die zu alt ist, diese entfernt werden und dann die neue installiert werden.

Grüße
Matthias

**Comment by descilla** [comment]
Which version of batctl was installed there? This information is essential because we parse the ``stdout`` of ``batctl -v`` and the output formatting may vary depending on installed version.

We should also do a real "lower than" version comparison instead of simply mismatching check. This will prevent us from downgrading if already a newer version that required is installed.

**Comment by MPW1412** [comment]
Weiß ich nicht mehr, hatte es gelöscht.

Prinzipiell hast du natürlich recht :)

**Comment by MPW1412** [comment]
Ah jetzt schon wieder:
```

TASK [gateways_batman : batctl bauen] ******************************************
fatal: [gw03]: FAILED! => {"failed": true, "msg": "The conditional check 'batctl.stat.exists == False or batctl_version.stdout_lines[0] != \"batctl 2016.4\"' failed. The error was: error while evaluating conditional (batctl.stat.exists == False or batctl_version.stdout_lines[0] != \"batctl 2016.4\"): 'dict object' has no attribute 'stdout_lines'\n\nThe error appears to have been in '/home/mpw/gits/ansible-fflip/roles/gateways_batman/tasks/main.yml': line 25, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: batctl bauen\n  ^ here\n"}
```

Voilà:

```
root@gw03 ~ # batctl -v
batctl 2016.4 [batman-adv: 2016.4]
```
War --check, vielleicht ist das das Problem, hab  es mir noch nicht weiter angesehen.

**Comment by descilla** [comment]
Ja, check_mode sollte für die vorherigen tasks (stat und shell) gesetzt sein.
Mir ist aber auch gerade aufgefallen, dass der Grep-Aufruf mit batctl versionen, die aus dem debian repo kommen nicht klar kommen wird:

```
# batctl -v
batctl debian-2016.5-1~bpo8+1 [batman-adv: 2016.2]
```

Wenn es nicht eilt, würde ich mir die ganze Sache morgen mal anschauen.

**Comment by HellMar** [comment]
Sollte sich erledigt haben da die Rolle ersetzt wurde.
