### ISSUE TITLE
bck-IP-Algorithmus knallt für vm_ids über 13

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/Ansible-Freifunk-Gateway#44]
Moin,

ich wollte gerade eine vm_id 14 vergeben, aber das macht der bck-Algorithmus nicht mit. Der generiert dann IPs über 255 im letzten Block.

@Fungur69, hättest du Lust dir das mal anzusehen? Die GRE-Dinger können ganz weg, eventuell sparen wir dadurch IPs. Sonst auf den /16er statt nur den /24er Block ausweichen.

Mir ist nicht ganz klar, warum wir da *20 gerechnet haben. Das klingt recht verschwenderisch.

Könnte man nicht einfach vm_id*2+0 bzw. +1 rechnen? Das wäre doch eindeutig, oder?

Viele Grüße
Matthias

**Comment by Fungur69** [comment]
@MPW1412 Der Algorithmus nimmt als letztes Byte der IP-Adresse `fremde_vm_id*20+eigene_vm_id*2` (bzw. wenn die eigene vm_id kleiner ist `eigene_vm_id*20+fremde_vm_id*2+1`). Der Algorithmus ist für eine max. vm_id von 10 ausgelegt. Bei 10 Backbone-Gateways hat jeder zu jedem anderen einen Tunnel, die alle untereinander eindeutige IPs brauchen, und dafür werden 90 IP-Adressen benötigt. Durch den Algorithmus werden dabei nicht alle Werte genutzt, so dass wir damit für 10 vm_ids schon zu einem Max. Wert von 200 kommen. Bei 16 Backbone-Gateways wären es 240 IPs. Man könnte einen Algorithmus bauen, der keine Werte auslässt: `((fremde_vm_id-2)*(fremde_vm_id-1)/2+eigene_vm_id)*2` bzw. für eigene vm_id kleiner fremde_vm_id `((eigene_vm_id-2)*(eigene_vm_id-1)/2+fremde_vm_id)*2+1`. Dann ist halt bei 16 Schluss. Wenn wir mehr vm_ids für Backbones brauchen, müssen wir einen größeren IP-Bereich dafür nutzen.

**Comment by MPW1412** [comment]
Lass uns das lieber über 192.168.0.0/16 so skalieren, dass wir bis 30 oder 40 keine Probleme haben.

**Comment by Fungur69** [comment]
192.168.`((fremde_vm_id-2)*(fremde_vm_id-1)/2+eigene_vm_id)/128`.`(((fremde_vm_id-2)*(fremde_vm_id-1)/2+eigene_vm_id)*2)%256` bzw. 192.168.`((eigene_vm_id-2)*(eigene_vm_id-1)/2+fremde_vm_id)/128`.`(((eigene_vm_id-2)*(eigene_vm_id-1)/2+fremde_vm_id)*2+1)%256`

Mit vm_id=40 ist das Max dann 192.168.5.206.

**Comment by MPW1412** [comment]
Top Danke.
