### ISSUE TITLE
build_tunnels_over_ipv6_if_available funktioniert nicht richtig.

### ISSUE THREAD

**Issue by igel1981** [FreiFunkMuenster/Ansible-Freifunk-Gateway#53]
Es wird bei den Verbindungen der Gateways zur Karte V4 mit V6 vermischt.

**Comment by HellMar** [comment]
675a5163e6262c21c5d7f67cb4d26661a5856d1a und f96909ea2830886851e41f9e51f6821b5945aba9 sowie https://github.com/FreiFunkMuenster/ansible-ffms/commit/e5a46f1608fcb560415fddc23b1cd66b68984948 sollte das beheben...
